#!/bin/bash

#  Block any staged files in node_modules
if git diff --cached --name-only | grep -q "^node_modules/"; then
  echo "❌ You tried to commit files in node_modules/. Don't."
  echo " node_modules should never be version controlled. Use .gitignore."
  exit 1
fi

exit 0