# GitHub Tasks Configuration
# This file configures task management and GitHub Issues integration

task_management:
  repository: adrianwedd/adrianwedd
  default_assignee: adrianwedd
  
  # Labels for task categorization
  labels:
    priority:
      high: "priority: high"
      medium: "priority: medium" 
      low: "priority: low"
    type:
      task: "type: task"
      enhancement: "type: enhancement"
      bug: "type: bug"
      documentation: "type: documentation"
    status:
      in_progress: "status: in-progress"
      blocked: "status: blocked"
    agent:
      claude: "agent: claude"
  
  # Task templates
  templates:
    bug_report:
      title: "Bug: {title}"
      labels: ["type: bug", "priority: medium"]
      body: |
        ## Bug Description
        {description}
        
        ## Steps to Reproduce
        1. {steps}
        
        ## Expected Behavior
        {expected}
        
        ## Actual Behavior
        {actual}
        
        ## Environment
        - Browser: {browser}
        - OS: {os}
        
        Generated by Claude Code task management
    
    enhancement:
      title: "Enhancement: {title}"
      labels: ["type: enhancement", "priority: low"]
      body: |
        ## Enhancement Request
        {description}
        
        ## Proposed Solution
        {solution}
        
        ## Benefits
        {benefits}
        
        Generated by Claude Code task management
    
    task:
      title: "Task: {title}"
      labels: ["type: task", "priority: medium"]
      body: |
        ## Task Description
        {description}
        
        ## Acceptance Criteria
        {criteria}
        
        ## Notes
        {notes}
        
        Generated by Claude Code task management

# Automation settings
automation:
  auto_create_from_todos: true
  sync_interval: "30m"
  close_completed_tasks: true
  
  # Workflows to trigger on task events
  workflows:
    on_task_created: "task-created.yml"
    on_task_updated: "task-updated.yml" 
    on_task_completed: "task-completed.yml"

# Integration settings
integrations:
  terminal_commands:
    create_task: "task create"
    list_tasks: "task list"
    update_task: "task update"
    close_task: "task close"
  
  ai_assistant:
    auto_categorize: true
    suggest_labels: true
    estimate_priority: true