name: 🤖 Interactive Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 🤖 Run Interactive Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Enhanced permissions for comprehensive development work
          additional_permissions: |
            actions: read
            contents: write
            issues: write
          
          # Use high-capability model for complex tasks
          model: "claude-sonnet-4-20250514"
          
          # Keep standard @claude trigger for interactive use
          trigger_phrase: "@claude"
          
          # Enhanced toolset for interactive development
          allowed_tools: |
            Bash(npm install)
            Bash(npm run build)
            Bash(npm run test:*)
            Bash(npm run lint:*)
            Bash(git add *)
            Bash(git commit *)
            Bash(gh issue close *)
          
          # Custom instructions for interactive mode
          custom_instructions: |
            🤖 **INTERACTIVE MODE** - Responding to @claude mentions
            
            **Capabilities:**
            - Code analysis, debugging, and implementation
            - Issue investigation and resolution
            - Test writing and CI/CD improvements
            - Documentation and architecture guidance
            - Pull request reviews and suggestions
            
            **Standards:**
            - Follow existing code patterns and architecture
            - Use sophisticated emoji for enhanced readability
            - Ensure accessibility and performance compliance
            - Run tests and maintain code quality
            - Provide comprehensive explanations and summaries
            - Use TodoWrite tool for complex multi-step tasks
            
            **Communication Style:**
            - Be concise but thorough
            - Use technical accuracy with clear explanations
            - Suggest improvements and best practices
            - Ask clarifying questions when requirements are unclear
            
            Note: For autonomous task completion, see the separate claude-autonomous.yml workflow.
          
          # Development environment
          claude_env: |
            NODE_ENV: development
            GITHUB_REPO: adrianwedd/adrianwedd

